/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.23.2
 * source: packet.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum MSGID {
    MSGBOX = 0,
    MOVEDATA = 1,
    JOINROOM = 2,
    JOINROOMREQ = 3,
    JOINROOMRES = 4,
    ROOMCREATED = 5,
    ROOMREMOVED = 6,
    CREATEROOMREQ = 7,
    CREATEROOMRES = 8,
    ROOMLISTREQ = 9,
    ROOMLISTRES = 10,
    QUITROOM = 11,
    PLAYGAMEREQ = 12,
    PLAYGAMERES = 13,
    SCENEREADY = 14,
    CONFIRMLOAD = 15
}
export enum PlayerType {
    NONE = 0,
    TARGET = 1,
    CHASER = 2
}
export class MsgBox extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        context?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("context" in data && data.context != undefined) {
                this.context = data.context;
            }
        }
    }
    get context() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set context(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        context?: string;
    }): MsgBox {
        const message = new MsgBox({});
        if (data.context != null) {
            message.context = data.context;
        }
        return message;
    }
    toObject() {
        const data: {
            context?: string;
        } = {};
        if (this.context != null) {
            data.context = this.context;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.context.length)
            writer.writeString(1, this.context);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgBox {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgBox();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.context = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): MsgBox {
        return MsgBox.deserialize(bytes);
    }
}
export class MoveData extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        id?: string;
        speed?: number;
        dir?: Position;
        pos?: Position;
        yRotation?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
            if ("speed" in data && data.speed != undefined) {
                this.speed = data.speed;
            }
            if ("dir" in data && data.dir != undefined) {
                this.dir = data.dir;
            }
            if ("pos" in data && data.pos != undefined) {
                this.pos = data.pos;
            }
            if ("yRotation" in data && data.yRotation != undefined) {
                this.yRotation = data.yRotation;
            }
        }
    }
    get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get speed() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set speed(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get dir() {
        return pb_1.Message.getWrapperField(this, Position, 3) as Position;
    }
    set dir(value: Position) {
        pb_1.Message.setWrapperField(this, 3, value);
    }
    get has_dir() {
        return pb_1.Message.getField(this, 3) != null;
    }
    get pos() {
        return pb_1.Message.getWrapperField(this, Position, 4) as Position;
    }
    set pos(value: Position) {
        pb_1.Message.setWrapperField(this, 4, value);
    }
    get has_pos() {
        return pb_1.Message.getField(this, 4) != null;
    }
    get yRotation() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set yRotation(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    static fromObject(data: {
        id?: string;
        speed?: number;
        dir?: ReturnType<typeof Position.prototype.toObject>;
        pos?: ReturnType<typeof Position.prototype.toObject>;
        yRotation?: number;
    }): MoveData {
        const message = new MoveData({});
        if (data.id != null) {
            message.id = data.id;
        }
        if (data.speed != null) {
            message.speed = data.speed;
        }
        if (data.dir != null) {
            message.dir = Position.fromObject(data.dir);
        }
        if (data.pos != null) {
            message.pos = Position.fromObject(data.pos);
        }
        if (data.yRotation != null) {
            message.yRotation = data.yRotation;
        }
        return message;
    }
    toObject() {
        const data: {
            id?: string;
            speed?: number;
            dir?: ReturnType<typeof Position.prototype.toObject>;
            pos?: ReturnType<typeof Position.prototype.toObject>;
            yRotation?: number;
        } = {};
        if (this.id != null) {
            data.id = this.id;
        }
        if (this.speed != null) {
            data.speed = this.speed;
        }
        if (this.dir != null) {
            data.dir = this.dir.toObject();
        }
        if (this.pos != null) {
            data.pos = this.pos.toObject();
        }
        if (this.yRotation != null) {
            data.yRotation = this.yRotation;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length)
            writer.writeString(1, this.id);
        if (this.speed != 0)
            writer.writeFloat(2, this.speed);
        if (this.has_dir)
            writer.writeMessage(3, this.dir, () => this.dir.serialize(writer));
        if (this.has_pos)
            writer.writeMessage(4, this.pos, () => this.pos.serialize(writer));
        if (this.yRotation != 0)
            writer.writeFloat(5, this.yRotation);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MoveData {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MoveData();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readString();
                    break;
                case 2:
                    message.speed = reader.readFloat();
                    break;
                case 3:
                    reader.readMessage(message.dir, () => message.dir = Position.deserialize(reader));
                    break;
                case 4:
                    reader.readMessage(message.pos, () => message.pos = Position.deserialize(reader));
                    break;
                case 5:
                    message.yRotation = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): MoveData {
        return MoveData.deserialize(bytes);
    }
}
export class Position extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        x?: number;
        y?: number;
        z?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("x" in data && data.x != undefined) {
                this.x = data.x;
            }
            if ("y" in data && data.y != undefined) {
                this.y = data.y;
            }
            if ("z" in data && data.z != undefined) {
                this.z = data.z;
            }
        }
    }
    get x() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set x(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get y() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set y(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get z() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set z(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
        x?: number;
        y?: number;
        z?: number;
    }): Position {
        const message = new Position({});
        if (data.x != null) {
            message.x = data.x;
        }
        if (data.y != null) {
            message.y = data.y;
        }
        if (data.z != null) {
            message.z = data.z;
        }
        return message;
    }
    toObject() {
        const data: {
            x?: number;
            y?: number;
            z?: number;
        } = {};
        if (this.x != null) {
            data.x = this.x;
        }
        if (this.y != null) {
            data.y = this.y;
        }
        if (this.z != null) {
            data.z = this.z;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.x != 0)
            writer.writeFloat(1, this.x);
        if (this.y != 0)
            writer.writeFloat(2, this.y);
        if (this.z != 0)
            writer.writeFloat(3, this.z);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Position {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Position();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.x = reader.readFloat();
                    break;
                case 2:
                    message.y = reader.readFloat();
                    break;
                case 3:
                    message.z = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Position {
        return Position.deserialize(bytes);
    }
}
export class CreateRoomReq extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        roomName?: string;
        maxUser?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("roomName" in data && data.roomName != undefined) {
                this.roomName = data.roomName;
            }
            if ("maxUser" in data && data.maxUser != undefined) {
                this.maxUser = data.maxUser;
            }
        }
    }
    get roomName() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set roomName(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get maxUser() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set maxUser(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        roomName?: string;
        maxUser?: number;
    }): CreateRoomReq {
        const message = new CreateRoomReq({});
        if (data.roomName != null) {
            message.roomName = data.roomName;
        }
        if (data.maxUser != null) {
            message.maxUser = data.maxUser;
        }
        return message;
    }
    toObject() {
        const data: {
            roomName?: string;
            maxUser?: number;
        } = {};
        if (this.roomName != null) {
            data.roomName = this.roomName;
        }
        if (this.maxUser != null) {
            data.maxUser = this.maxUser;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.roomName.length)
            writer.writeString(1, this.roomName);
        if (this.maxUser != 0)
            writer.writeInt32(2, this.maxUser);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateRoomReq {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CreateRoomReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.roomName = reader.readString();
                    break;
                case 2:
                    message.maxUser = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): CreateRoomReq {
        return CreateRoomReq.deserialize(bytes);
    }
}
export class CreateRoomRes extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        success?: boolean;
        room?: Room;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("success" in data && data.success != undefined) {
                this.success = data.success;
            }
            if ("room" in data && data.room != undefined) {
                this.room = data.room;
            }
        }
    }
    get success() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set success(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get room() {
        return pb_1.Message.getWrapperField(this, Room, 2) as Room;
    }
    set room(value: Room) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    get has_room() {
        return pb_1.Message.getField(this, 2) != null;
    }
    static fromObject(data: {
        success?: boolean;
        room?: ReturnType<typeof Room.prototype.toObject>;
    }): CreateRoomRes {
        const message = new CreateRoomRes({});
        if (data.success != null) {
            message.success = data.success;
        }
        if (data.room != null) {
            message.room = Room.fromObject(data.room);
        }
        return message;
    }
    toObject() {
        const data: {
            success?: boolean;
            room?: ReturnType<typeof Room.prototype.toObject>;
        } = {};
        if (this.success != null) {
            data.success = this.success;
        }
        if (this.room != null) {
            data.room = this.room.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.success != false)
            writer.writeBool(1, this.success);
        if (this.has_room)
            writer.writeMessage(2, this.room, () => this.room.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateRoomRes {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CreateRoomRes();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.success = reader.readBool();
                    break;
                case 2:
                    reader.readMessage(message.room, () => message.room = Room.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): CreateRoomRes {
        return CreateRoomRes.deserialize(bytes);
    }
}
export class JoinRoom extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        id?: string;
        userCount?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
            if ("userCount" in data && data.userCount != undefined) {
                this.userCount = data.userCount;
            }
        }
    }
    get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get userCount() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set userCount(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        id?: string;
        userCount?: number;
    }): JoinRoom {
        const message = new JoinRoom({});
        if (data.id != null) {
            message.id = data.id;
        }
        if (data.userCount != null) {
            message.userCount = data.userCount;
        }
        return message;
    }
    toObject() {
        const data: {
            id?: string;
            userCount?: number;
        } = {};
        if (this.id != null) {
            data.id = this.id;
        }
        if (this.userCount != null) {
            data.userCount = this.userCount;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length)
            writer.writeString(1, this.id);
        if (this.userCount != 0)
            writer.writeInt32(2, this.userCount);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): JoinRoom {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new JoinRoom();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readString();
                    break;
                case 2:
                    message.userCount = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): JoinRoom {
        return JoinRoom.deserialize(bytes);
    }
}
export class JoinRoomReq extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        roomName?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("roomName" in data && data.roomName != undefined) {
                this.roomName = data.roomName;
            }
        }
    }
    get roomName() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set roomName(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        roomName?: string;
    }): JoinRoomReq {
        const message = new JoinRoomReq({});
        if (data.roomName != null) {
            message.roomName = data.roomName;
        }
        return message;
    }
    toObject() {
        const data: {
            roomName?: string;
        } = {};
        if (this.roomName != null) {
            data.roomName = this.roomName;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.roomName.length)
            writer.writeString(1, this.roomName);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): JoinRoomReq {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new JoinRoomReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.roomName = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): JoinRoomReq {
        return JoinRoomReq.deserialize(bytes);
    }
}
export class JoinRoomRes extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        success?: boolean;
        room?: Room;
        userList?: string[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("success" in data && data.success != undefined) {
                this.success = data.success;
            }
            if ("room" in data && data.room != undefined) {
                this.room = data.room;
            }
            if ("userList" in data && data.userList != undefined) {
                this.userList = data.userList;
            }
        }
    }
    get success() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set success(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get room() {
        return pb_1.Message.getWrapperField(this, Room, 2) as Room;
    }
    set room(value: Room) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    get has_room() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get userList() {
        return pb_1.Message.getFieldWithDefault(this, 3, []) as string[];
    }
    set userList(value: string[]) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
        success?: boolean;
        room?: ReturnType<typeof Room.prototype.toObject>;
        userList?: string[];
    }): JoinRoomRes {
        const message = new JoinRoomRes({});
        if (data.success != null) {
            message.success = data.success;
        }
        if (data.room != null) {
            message.room = Room.fromObject(data.room);
        }
        if (data.userList != null) {
            message.userList = data.userList;
        }
        return message;
    }
    toObject() {
        const data: {
            success?: boolean;
            room?: ReturnType<typeof Room.prototype.toObject>;
            userList?: string[];
        } = {};
        if (this.success != null) {
            data.success = this.success;
        }
        if (this.room != null) {
            data.room = this.room.toObject();
        }
        if (this.userList != null) {
            data.userList = this.userList;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.success != false)
            writer.writeBool(1, this.success);
        if (this.has_room)
            writer.writeMessage(2, this.room, () => this.room.serialize(writer));
        if (this.userList.length)
            writer.writeRepeatedString(3, this.userList);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): JoinRoomRes {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new JoinRoomRes();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.success = reader.readBool();
                    break;
                case 2:
                    reader.readMessage(message.room, () => message.room = Room.deserialize(reader));
                    break;
                case 3:
                    pb_1.Message.addToRepeatedField(message, 3, reader.readString());
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): JoinRoomRes {
        return JoinRoomRes.deserialize(bytes);
    }
}
export class RoomListReq extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {}) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") { }
    }
    static fromObject(data: {}): RoomListReq {
        const message = new RoomListReq({});
        return message;
    }
    toObject() {
        const data: {} = {};
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RoomListReq {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RoomListReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): RoomListReq {
        return RoomListReq.deserialize(bytes);
    }
}
export class RoomListRes extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        list?: Room[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("list" in data && data.list != undefined) {
                this.list = data.list;
            }
        }
    }
    get list() {
        return pb_1.Message.getRepeatedWrapperField(this, Room, 1) as Room[];
    }
    set list(value: Room[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    static fromObject(data: {
        list?: ReturnType<typeof Room.prototype.toObject>[];
    }): RoomListRes {
        const message = new RoomListRes({});
        if (data.list != null) {
            message.list = data.list.map(item => Room.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            list?: ReturnType<typeof Room.prototype.toObject>[];
        } = {};
        if (this.list != null) {
            data.list = this.list.map((item: Room) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.list.length)
            writer.writeRepeatedMessage(1, this.list, (item: Room) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RoomListRes {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RoomListRes();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.list, () => pb_1.Message.addToRepeatedWrapperField(message, 1, Room.deserialize(reader), Room));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): RoomListRes {
        return RoomListRes.deserialize(bytes);
    }
}
export class QuitRoom extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        id?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
        }
    }
    get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        id?: string;
    }): QuitRoom {
        const message = new QuitRoom({});
        if (data.id != null) {
            message.id = data.id;
        }
        return message;
    }
    toObject() {
        const data: {
            id?: string;
        } = {};
        if (this.id != null) {
            data.id = this.id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length)
            writer.writeString(1, this.id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QuitRoom {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new QuitRoom();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): QuitRoom {
        return QuitRoom.deserialize(bytes);
    }
}
export class RoomRemoved extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        roomName?: string;
        isYourRoom?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("roomName" in data && data.roomName != undefined) {
                this.roomName = data.roomName;
            }
            if ("isYourRoom" in data && data.isYourRoom != undefined) {
                this.isYourRoom = data.isYourRoom;
            }
        }
    }
    get roomName() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set roomName(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get isYourRoom() {
        return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
    }
    set isYourRoom(value: boolean) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        roomName?: string;
        isYourRoom?: boolean;
    }): RoomRemoved {
        const message = new RoomRemoved({});
        if (data.roomName != null) {
            message.roomName = data.roomName;
        }
        if (data.isYourRoom != null) {
            message.isYourRoom = data.isYourRoom;
        }
        return message;
    }
    toObject() {
        const data: {
            roomName?: string;
            isYourRoom?: boolean;
        } = {};
        if (this.roomName != null) {
            data.roomName = this.roomName;
        }
        if (this.isYourRoom != null) {
            data.isYourRoom = this.isYourRoom;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.roomName.length)
            writer.writeString(1, this.roomName);
        if (this.isYourRoom != false)
            writer.writeBool(2, this.isYourRoom);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RoomRemoved {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RoomRemoved();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.roomName = reader.readString();
                    break;
                case 2:
                    message.isYourRoom = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): RoomRemoved {
        return RoomRemoved.deserialize(bytes);
    }
}
export class Room extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        name?: string;
        userCount?: number;
        maxCount?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("name" in data && data.name != undefined) {
                this.name = data.name;
            }
            if ("userCount" in data && data.userCount != undefined) {
                this.userCount = data.userCount;
            }
            if ("maxCount" in data && data.maxCount != undefined) {
                this.maxCount = data.maxCount;
            }
        }
    }
    get name() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set name(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get userCount() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set userCount(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get maxCount() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set maxCount(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
        name?: string;
        userCount?: number;
        maxCount?: number;
    }): Room {
        const message = new Room({});
        if (data.name != null) {
            message.name = data.name;
        }
        if (data.userCount != null) {
            message.userCount = data.userCount;
        }
        if (data.maxCount != null) {
            message.maxCount = data.maxCount;
        }
        return message;
    }
    toObject() {
        const data: {
            name?: string;
            userCount?: number;
            maxCount?: number;
        } = {};
        if (this.name != null) {
            data.name = this.name;
        }
        if (this.userCount != null) {
            data.userCount = this.userCount;
        }
        if (this.maxCount != null) {
            data.maxCount = this.maxCount;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.name.length)
            writer.writeString(1, this.name);
        if (this.userCount != 0)
            writer.writeInt32(2, this.userCount);
        if (this.maxCount != 0)
            writer.writeInt32(3, this.maxCount);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Room {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Room();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.name = reader.readString();
                    break;
                case 2:
                    message.userCount = reader.readInt32();
                    break;
                case 3:
                    message.maxCount = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Room {
        return Room.deserialize(bytes);
    }
}
export class PlayGameReq extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        playTime?: number;
        targetHp?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("playTime" in data && data.playTime != undefined) {
                this.playTime = data.playTime;
            }
            if ("targetHp" in data && data.targetHp != undefined) {
                this.targetHp = data.targetHp;
            }
        }
    }
    get playTime() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set playTime(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get targetHp() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set targetHp(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        playTime?: number;
        targetHp?: number;
    }): PlayGameReq {
        const message = new PlayGameReq({});
        if (data.playTime != null) {
            message.playTime = data.playTime;
        }
        if (data.targetHp != null) {
            message.targetHp = data.targetHp;
        }
        return message;
    }
    toObject() {
        const data: {
            playTime?: number;
            targetHp?: number;
        } = {};
        if (this.playTime != null) {
            data.playTime = this.playTime;
        }
        if (this.targetHp != null) {
            data.targetHp = this.targetHp;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.playTime != 0)
            writer.writeInt32(1, this.playTime);
        if (this.targetHp != 0)
            writer.writeInt32(2, this.targetHp);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PlayGameReq {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PlayGameReq();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.playTime = reader.readInt32();
                    break;
                case 2:
                    message.targetHp = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PlayGameReq {
        return PlayGameReq.deserialize(bytes);
    }
}
export class PlayGameRes extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        success?: boolean;
        type?: PlayerType;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("success" in data && data.success != undefined) {
                this.success = data.success;
            }
            if ("type" in data && data.type != undefined) {
                this.type = data.type;
            }
        }
    }
    get success() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set success(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get type() {
        return pb_1.Message.getFieldWithDefault(this, 2, PlayerType.NONE) as PlayerType;
    }
    set type(value: PlayerType) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        success?: boolean;
        type?: PlayerType;
    }): PlayGameRes {
        const message = new PlayGameRes({});
        if (data.success != null) {
            message.success = data.success;
        }
        if (data.type != null) {
            message.type = data.type;
        }
        return message;
    }
    toObject() {
        const data: {
            success?: boolean;
            type?: PlayerType;
        } = {};
        if (this.success != null) {
            data.success = this.success;
        }
        if (this.type != null) {
            data.type = this.type;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.success != false)
            writer.writeBool(1, this.success);
        if (this.type != PlayerType.NONE)
            writer.writeEnum(2, this.type);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PlayGameRes {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PlayGameRes();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.success = reader.readBool();
                    break;
                case 2:
                    message.type = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PlayGameRes {
        return PlayGameRes.deserialize(bytes);
    }
}
export class SceneReady extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {}) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") { }
    }
    static fromObject(data: {}): SceneReady {
        const message = new SceneReady({});
        return message;
    }
    toObject() {
        const data: {} = {};
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SceneReady {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SceneReady();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SceneReady {
        return SceneReady.deserialize(bytes);
    }
}
export class ConfirmLoad extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {}) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") { }
    }
    static fromObject(data: {}): ConfirmLoad {
        const message = new ConfirmLoad({});
        return message;
    }
    toObject() {
        const data: {} = {};
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ConfirmLoad {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ConfirmLoad();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ConfirmLoad {
        return ConfirmLoad.deserialize(bytes);
    }
}
